---
language: python
python:
  - "2.7"
sudo: required
before_install:
  - ./install-bgpq3.sh
install:
  - pip install -r packaging/requirements-test.txt
  - pip install -e .
script:
  - nosetests --with-coverage --cover-inclusive
after_success:
  - codecov
notifications:
  slack: wolcomm:yFzhM9JrnJsYw11xMcStIuZU
...