language: python
sudo: required
matrix:
  fast_finish: true
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial
  allow_failures:
    - python: "3.7"
    - python: "3.8-dev"
before_install:
- sudo apt-get -qq update
- "./utils/install-bgpq3.sh"
install:
- pip install -U pip
- pip install -U setuptools
- pip install tox-travis codecov
script:
- tox
after_success:
- codecov
notifications:
  email: false
  slack:
    rooms:
      secure: UB3qyc1GSdnH1nQ9kSWgl31rWVW0t/9Dy8VVluHM3wIYG3JYFuZEPKBjjWlbo9J3q7rqP0WFsdRJDcBqzexzgtZ/auGRpAwiUYYjbBkMQ8Nkv0L7XSsBPrGOHqALw2xuZeaAPKJUWv4F61Tdj3bt+uTNJKuWf/LeD8/Er961bxQ7Ey6Fj+k75bsQ9IxFnEhJWcumb7a4k9E/S4h88/z1fOr7CIByOHo4rLjBmKsnzb/GrsqbZzyawEqn0+rD0rwQhUGYVMovCxWoq4biq9cQWn/KrlLgfPM3+7bm5JJCzPu0Y8S/Hs4EsyGAXy7xmyXDk/ySGYiNt7xbrjXzKQD1cX79IZ0TffT23Vwn+xQAg2Hg/PMikapFGR5rPTWcY3NnuGAbEo1a7GTkhGvZ5kgFM3k0Ap5aiSb50G/tCo/CMtmGDxkZIrl287z3LvPLyv3WTK2UxfSBACC69qkKFiLD9ljbtDL1VenMlrUo2KQ3MvuD8WP8sBmE30NW2xv7SdE7aoCiemZRMSEQU8dgdLbATxe8+dUBG0HmLxkhCr6bHwpvlIzJ5DnAQu6js7AuYTtTo7i+MWC/nTayQQyqNl8fj9G2F4UNSJX6U0RxMaXZ0Ca7zs+qSxQzTxErYo59GTBhtw/mYEOZqxtC9a++VUFWRfhGZpoInNJREmNF55+IKBE=
deploy:
  provider: pypi
  user: benmaddison
  distributions: sdist bdist_wheel
  password:
    secure: GEqvkvLr93FF59D1Uar81CerFCiVZ2riqqjpM+UuJrlGPEkBldH4lcyxeBg6ySBn+avr0vbs56g1BHTomKZT+7GAUIvSTwH5C4pXuGBW/Bb965pfxrI1jQjvW4RNUS25G5mKpcNO3057xtBFz+ttQMOwrpOm7ISetpJ7vDgU5vERsQVNvoX0jPWujDv2QcDkFE8UHwbFtTj02ZBAMG1MCiTRa1wLLIhNuEv9lcp2/ptqqWa+H4OMK44TZ4P+89h769AgjphKhZ22Nr4bqH1S6GuHJvie0skOnqlEcPjk2XTlxSNqTlN7cL9pflzPtA/Yu2XypovLzX3cgbYHA0G1jhDYhvPNs65v+6uRJsTpNnUmZr5hWNi/3eojOnZwEdetp7jAPR6Bn66UXlnO2tJgZHy+aM9cx8UogURrrtBdj+FPKZN61D/unWw69zckNF21t2ktYBlncQJ8x8QyukyM+09Gnudr6US+PVmB/43tOeEtObMx3tGrk6HVrKcr84wbitV92bSIwvz7CGePObrNJWd1OvD70jYQDrUjGgwSdRUaculeRA6j2LMmynvTvpNHli+G3B61QGHVJ24nbKODRQQHFjvN3UhYhurHgNYGh2iETJot4u/3K4jhzP7B6yW7xQQnkv0i9bfj1/QdO26FVse2+0taVOeuJYad95w4FjM=
  on:
    tags: true
    python: '2.7'
