---
language: python
python:
  - "2.7"
sudo: required
before_install:
  - ./install-bgpq3.sh
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov
notifications:
  slack: wolcomm:yFzhM9JrnJsYw11xMcStIuZU
...
