codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
  notify:
    slack:
      default:
        url: https://hooks.slack.com/services/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
        threshold: 0
        attachments: "sunburst, diff"
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
