codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
  notify:
    slack:
      default:
        url: secret:0RAKRZk+BiTQWVZJs1p8FeiiUWkZQk8H29Mkmk2Iw13JqYliusndes5oKq4fwdhhsPPX6wYjP1IWs8RBu8rK1s25Vh/ata45e0teIXSYByuHCnmy09vM7TECxzQfrEGKsbq2q0xcCk4zGJl+z3TKj45kGC9e+SoLtDhZ3kILYCY=
        threshold: 0
        attachments: "sunburst, diff"
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
